// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Pony code generator — produces .pony files from parsed actor/behaviour definitions.
//
// Generates syntactically correct Pony source code with:
// - Actor declarations with typed fields and capability annotations
// - Behaviour declarations with parameter capabilities
// - Constructors (create behaviours)
// - Proper Pony formatting and documentation comments

use anyhow::{Context, Result};
use std::fmt::Write;

use crate::abi::{Actor, Behaviour, RefCapability};
use crate::codegen::parser::ParsedDefinitions;

/// Options controlling Pony code generation.
#[derive(Debug, Clone)]
pub struct GenerationOptions {
    /// Whether to include documentation comments in generated code.
    pub include_docs: bool,
    /// Whether to generate a Main actor if one is not defined.
    pub generate_main: bool,
    /// Header comment to include at the top of each generated file.
    pub header_comment: String,
}

impl Default for GenerationOptions {
    fn default() -> Self {
        GenerationOptions {
            include_docs: true,
            generate_main: false,
            header_comment: String::from(
                "// Generated by ponyiser — Pony reference capability wrapper generator\n\
                 // SPDX-License-Identifier: PMPL-1.0-or-later\n\
                 // DO NOT EDIT — regenerate with `ponyiser generate`\n",
            ),
        }
    }
}

/// Generated Pony source file.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    /// Filename (e.g., "connection_manager.pony").
    pub filename: String,
    /// Full Pony source code content.
    pub content: String,
}

/// Generate Pony source files for all actors and their behaviours.
///
/// Each actor produces one .pony file containing:
/// - The actor declaration with fields
/// - A `create` constructor behaviour
/// - All behaviours defined for that actor
///
/// Returns a vector of generated files ready to be written to disk.
pub fn generate_pony_files(
    defs: &ParsedDefinitions,
    options: &GenerationOptions,
) -> Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();

    for actor in &defs.actors {
        let actor_behaviours: Vec<&Behaviour> = defs
            .behaviours
            .iter()
            .filter(|b| b.actor == actor.name)
            .collect();

        let content = generate_actor_file(actor, &actor_behaviours, options)
            .with_context(|| format!("Failed to generate Pony for actor '{}'", actor.name))?;

        let filename = format!("{}.pony", to_snake_case(&actor.name));
        files.push(GeneratedFile { filename, content });
    }

    Ok(files)
}

/// Generate a single .pony file for one actor and its behaviours.
fn generate_actor_file(
    actor: &Actor,
    behaviours: &[&Behaviour],
    options: &GenerationOptions,
) -> Result<String> {
    let mut output = String::new();

    // File header.
    output.push_str(&options.header_comment);
    output.push('\n');

    // Actor documentation.
    if options.include_docs
        && let Some(ref doc) = actor.doc
    {
        for line in doc.as_str().lines() {
            writeln!(output, "  \"\"\" {} \"\"\"", line)?;
        }
    }

    // Actor declaration.
    writeln!(output, "actor {}", actor.name)?;

    // Field declarations.
    if !actor.fields.is_empty() {
        for field in &actor.fields {
            let pony_type = to_pony_type(&field.field_type, field.capability);
            if options.include_docs {
                writeln!(
                    output,
                    "  // Field '{}' with capability '{}'",
                    field.name, field.capability
                )?;
            }
            writeln!(output, "  var _{}: {}", field.name, pony_type)?;
        }
        writeln!(output)?;
    }

    // Constructor (new create).
    generate_constructor(&mut output, actor, options)?;

    // Behaviour declarations.
    for behaviour in behaviours {
        // Skip if it's a 'create' behaviour (already generated as constructor).
        if behaviour.name == "create" {
            continue;
        }
        generate_behaviour(&mut output, behaviour, options)?;
    }

    Ok(output)
}

/// Generate a `new create` constructor for an actor.
///
/// The constructor initialises all fields. Fields with capability iso
/// use `recover` blocks, fields with val use literal defaults, and
/// ref fields are initialised to their type's default.
fn generate_constructor(
    output: &mut String,
    actor: &Actor,
    options: &GenerationOptions,
) -> Result<()> {
    if options.include_docs {
        writeln!(output, "  // Constructor — initialises actor state")?;
    }
    write!(output, "  new create(")?;

    // Constructor parameters: one for each field that needs initialisation.
    let params: Vec<String> = actor
        .fields
        .iter()
        .map(|f| {
            let pony_type = to_pony_type(&f.field_type, f.capability);
            format!("{}_init: {}", f.name, pony_type)
        })
        .collect();
    write!(output, "{}", params.join(", "))?;
    writeln!(output, ") =>")?;

    // Field assignments.
    for field in &actor.fields {
        writeln!(output, "    _{} = {}_init", field.name, field.name)?;
    }
    if actor.fields.is_empty() {
        writeln!(output, "    None")?;
    }
    writeln!(output)?;

    Ok(())
}

/// Generate a behaviour declaration.
///
/// Behaviours are asynchronous message handlers. Parameters are annotated
/// with their required reference capabilities.
fn generate_behaviour(
    output: &mut String,
    behaviour: &Behaviour,
    options: &GenerationOptions,
) -> Result<()> {
    if options.include_docs
        && let Some(ref doc) = behaviour.doc
    {
        writeln!(output, "  // {}", doc)?;
    }

    write!(output, "  be {}(", behaviour.name)?;

    let params: Vec<String> = behaviour
        .params
        .iter()
        .map(|p| {
            let pony_type = to_pony_type(&p.param_type, p.capability);
            format!("{}: {}", p.name, pony_type)
        })
        .collect();
    write!(output, "{}", params.join(", "))?;
    writeln!(output, ") =>")?;

    // Body placeholder — users fill in the implementation.
    writeln!(
        output,
        "    // TODO: implement behaviour '{}'",
        behaviour.name
    )?;
    writeln!(output, "    None")?;
    writeln!(output)?;

    Ok(())
}

/// Convert a type string and capability to a Pony type annotation.
///
/// Maps common type patterns to Pony equivalents with capability suffixes.
/// Examples:
///   ("String", val) -> "String val"
///   ("Array[U8]", iso) -> "Array[U8] iso"
///   ("U64", val) -> "U64 val"
fn to_pony_type(type_str: &str, capability: RefCapability) -> String {
    format!("{} {}", type_str, capability)
}

/// Convert a PascalCase name to snake_case for filenames.
///
/// Examples:
///   "ConnectionManager" -> "connection_manager"
///   "TCPListener" -> "tcp_listener"
///   "Main" -> "main"
fn to_snake_case(name: &str) -> String {
    let mut result = String::new();
    let mut prev_was_upper = false;

    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 && !prev_was_upper {
                result.push('_');
            }
            // Handle consecutive uppercase: "TCP" -> "tcp" not "t_c_p".
            if i > 0 && prev_was_upper {
                // Check if next char is lowercase (end of acronym).
                let next_is_lower = name
                    .chars()
                    .nth(i + 1)
                    .map(|c| c.is_ascii_lowercase())
                    .unwrap_or(false);
                if next_is_lower {
                    result.push('_');
                }
            }
            result.push(ch.to_ascii_lowercase());
            prev_was_upper = true;
        } else {
            result.push(ch);
            prev_was_upper = false;
        }
    }

    result
}

/// Generate a complete Pony package from parsed definitions.
///
/// This is the high-level entry point used by the codegen module.
/// It generates all .pony files and returns them as a vector.
pub fn generate_package(defs: &ParsedDefinitions) -> Result<Vec<GeneratedFile>> {
    let options = GenerationOptions::default();
    generate_pony_files(defs, &options)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{Actor, Behaviour, BehaviourParam, Field, RefCapability};
    use crate::codegen::parser::ParsedDefinitions;
    use std::collections::HashMap;

    fn make_test_defs() -> ParsedDefinitions {
        let actors = vec![Actor {
            name: "Greeter".to_string(),
            fields: vec![Field {
                name: "greeting".to_string(),
                field_type: "String".to_string(),
                capability: RefCapability::Val,
            }],
            doc: Some("A simple greeting actor".to_string()),
        }];
        let behaviours = vec![Behaviour {
            actor: "Greeter".to_string(),
            name: "greet".to_string(),
            params: vec![BehaviourParam {
                name: "name".to_string(),
                param_type: "String".to_string(),
                capability: RefCapability::Val,
            }],
            capability_requirements: vec![],
            doc: Some("Send a greeting".to_string()),
        }];

        let mut actor_index = HashMap::new();
        actor_index.insert("Greeter".to_string(), 0);
        let mut behaviour_index = HashMap::new();
        behaviour_index.insert(("Greeter".to_string(), "greet".to_string()), 0);

        ParsedDefinitions {
            actors,
            behaviours,
            actor_index,
            behaviour_index,
        }
    }

    #[test]
    fn test_generate_pony_files() {
        let defs = make_test_defs();
        let files = generate_pony_files(&defs, &GenerationOptions::default()).unwrap();
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].filename, "greeter.pony");
        assert!(files[0].content.contains("actor Greeter"));
        assert!(files[0].content.contains("var _greeting: String val"));
        assert!(files[0].content.contains("be greet(name: String val)"));
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("Main"), "main");
        assert_eq!(to_snake_case("ConnectionManager"), "connection_manager");
        assert_eq!(to_snake_case("TCPListener"), "tcp_listener");
    }

    #[test]
    fn test_to_pony_type() {
        assert_eq!(to_pony_type("String", RefCapability::Val), "String val");
        assert_eq!(
            to_pony_type("Array[U8]", RefCapability::Iso),
            "Array[U8] iso"
        );
    }
}
